### PR TITLE
Fixing two tiny typos

### PR DESCRIPTION
**Pull request by ginkogruen**
Fixed two tiny errors I stumbled upon.
A misspelling in `README.md` and a whitespace error in `options.json` which could lead to confusion about the name of the tmux config file (... to add totmux.conf --> ... to add to tmux.conf).

### CODE REVIEW

**Comment by mipmip** [comment]
The option are autogenerated. You should fix this typo in the home manager project. Thanks for PR.

**Comment by ginkogruen** [comment]
Ok, will do thanks :)

**Comment by ginkogruen** [comment]
@mipmip I just looked at the `tmux.nix` source and it seems that every time there's a linebreak in the file it ends up as a whitespace error on the website. I thought the *totmux.conf* was a singular error but it happens all over the place.

Here's an example of how it looks in the `tmux.nix` file:

``` nix
extraConfig = mkOption {
        type = types.lines;
        default = "";
        description = ''
          Additional configuration to add to
          {file}`tmux.conf`.
        '';
      };

```

It also happens on other files such as the `fuzzel.nix` for example.
Do you think this formatting error is on home-manager or could it have something to do with how the `options.json` is generated?
Because when I view the option through `man home-configuration.nix` it looks correct.

**Comment by mipmip** [comment]
In that case this should be a parser problem. This shall be addressed when #20 is realized. This is a high priority issue. Will work on this ASAP.

**Comment by ginkogruen** [comment]
Looking forward to it. This project is really useful.

**Pull request merged**
